`include "DV/common/test_params.vh"
`timescale 1ns / 1ps  // Define the time unit and precision

module tea_core_tb();

    // Signals to connect to the TEA Core
    reg clk;
    reg rst_n;
    reg mode; // 0 for encrypt, 1 for decrypt
    reg start;
    reg [63:0] plaintext;
    reg [127:0] key;
    
    wire [63:0] ciphertext;
    wire valid;
    wire ready;

    reg [255:0] test_vectors [0:`NUM_TESTS - 1]; // Adjust size to match your N
    integer i;

    // Instantiate the UUT
    tea_core uut (
        .clk(clk),
        .rst_n(rst_n),
        .mode(mode),
        .start(start),
        .plaintext(plaintext),
        .key(key),
        .ciphertext(ciphertext),
        .valid(valid),
        .ready(ready)
    );

    task run_test(input [127:0] t_key, input [63:0] t_pt, input [63:0] t_expected, input t_mode);
    begin
        wait(ready == 1);
        #10;
        @(posedge clk);
        key = t_key;
        plaintext = t_pt;
        mode = t_mode;
        start = 1;
        @(posedge clk);
        start = 0;
        
        wait(valid == 1);
        @(posedge clk);
        #10; // Wait for settle
        if (ciphertext == t_expected)
            $display("PASS | PT: %h | CT: %h", t_pt, ciphertext);
        else
            $display("FAIL | PT: %h | Expected: %h | Got: %h", t_pt, t_expected, ciphertext);
        
        @(posedge clk);
    end
    endtask

    
    // This creates a 100MHz clock (10ns period)
    always #5 clk = ~clk;

    // The Test Scenario
    initial begin
        $dumpfile("build/iterative/tea_waves.vcd"); 
        $dumpvars(0, tea_core_tb);

        // Load test vectors from the file generated by gen_vectors.py
        $readmemh("DV/common/tea_tests.mem", test_vectors);

        // Initialize signals
        clk = 0;
        rst_n = 0;
        mode = 0;
        start = 0;
        i = 0;
        key = 128'd0;
        plaintext = 64'd0;

        // Set reset high
        #20;
        rst_n = 1;
        #20;

        $display("Starting Encryption Tests...");
        for (i = 0; i < `NUM_TESTS; i = i + 1) begin
            $display("--- Encryption Test Vector %0d ---", i+1);
            
            // Extract fields from the array index
            // Key is top 128 bits, PT is middle 64, CT is bottom 64
            run_test(
                test_vectors[i][255:128], // Key
                test_vectors[i][127:64],  // Plaintext
                test_vectors[i][63:0],    // Expected Ciphertext
                1'b0                      // Mode (0 for encryption)
            );
        end
        
        $display("Starting Decryption Tests...");
        for (i = 0; i < `NUM_TESTS; i = i + 1) begin
            $display("--- Decryption Test Vector %0d ---", i+1);
            
            // Extract fields from the array index
            // Key is top 128 bits, PT is middle 64, CT is bottom 64
            run_test(
                test_vectors[i][255:128], // Key
                test_vectors[i][63:0],    // Ciphertext
                test_vectors[i][127:64],  // Expected Plaintext
                1'b1                      // Mode (1 for decryption)
            );
        end

        $display("All tests completed!");
        $finish;
    end

endmodule